const char *ber_tagclass_names[] = {
	"Universal",
	"Application",
	"Context-specific",
	"Private"
};

const char *ber_tagtype_names[] = {
	"End of Content",
	"Boolean",
	"Integer",
	"Bit String",
	"Octet String",
	"Null",
	"Object Identifier (OID)",
	"Object Descriptor",
	"External",
	"Real",
	"Enumerated",
	"Embedded PDV",
	"UTF8 String",
	"Relative OID",
	"Time",
	"RESERVED",
	"Sequence",
	"Set",
	"Numeric String",
	"Printable String",
	"T61 String",
	"Videotex String",
	"IA5 String",
	"UTC Time",
	"Generalized Time",
	"Graphic String",
	"Visible String",
	"General String",
	"Universal String",
	"Character String",
	"BMP String",
	"Date",
	"Time of Day",
	"Datetime",
	"Duration",
	"OID IRI",
	"Relative OID IRI",
};
